### ISSUE TITLE
Crash on startup 1.19.2 Forge

### ISSUE THREAD

**Issue by ZedoxPapaia** [RadonCoding/origins-extra-keybinds-forge#1]
Crash as soon as clicking play, exit code 1.

Error message:
[main/FATAL]: Failed to parse version spec [1.19.2)
org.apache.maven.artifact.versioning.InvalidVersionSpecificationException: Single version must be surrounded by []: [1.19.2)

**Comment by RadonCoding** [comment]
Fixed going to take a while for CurseForge to approve.
